service: notes-crud-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  profile: perpion-sanka
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  createNote:
    handler: handler.createNote
    events:
      - http:
          method: post
          path: notes

  UpdateNote:
    handler: handler.updateNote
    events:
      - http:
          method: put
          path: notes/{id}
